include:
- project: 'zerocube/gitlab-ci'
  ref: master
  file: '/docker.yml'

stages:
- build
- publish

Docker Build:
  extends: .Docker - Build

Publish to Docker Hub:
  extends: .Docker - Base
  stage: publish
  variables:
    DOCKER_HUB_IMAGE: "zerocube/ffmpeg"
  before_script:
  - export HUB_IMAGE_URL="${DOCKER_HUB_REGISTRY}/${DOCKER_HUB_IMAGE}:latest"
  script:
  - docker pull "${DOCKER_IMAGE}"
  - >
    docker login
    -u "${DOCKER_HUB_USERNAME}"
    -p "${DOCKER_HUB_PASSWORD}"
    registry.hub.docker.com
  - docker tag "${DOCKER_IMAGE}" "${HUB_IMAGE_URL}"
  - docker push "${HUB_IMAGE_URL}"
  only:
  - master

Publish to GitHub:
  image: alpine:3.7
  stage: publish
  before_script:
  - export SSH_DIR="${HOME}/.ssh"
  - export TMP_DIR="/tmp/repoclone"
  - apk add --update git openssh
  script:
  - '[ ! -d "${SSH_DIR}" ] && mkdir -p "${SSH_DIR}"'
  - >
    echo -n "${SSH_ZEROCUBE_DELIVERY_PRIVATE_KEY}" |
    base64 -d > "${SSH_DIR}/id_rsa"
  - chmod 600 "${SSH_DIR}/id_rsa"
  - cp ssh_config "${SSH_DIR}/config"
  - git config user.name "${GITLAB_USER_NAME} (${GITLAB_USER_LOGIN})"
  - git config user.email "${GITLAB_USER_EMAIL}"
  - git clone --bare "git@gitlab.com:${CI_PROJECT_PATH}" "${TMP_DIR}"
  - cd "${TMP_DIR}"
  - 'git push --mirror "${GITHUB_REPO}"'
  only:
  - master
