image: docker:latest

stages:
  - build
  - publish

services:
  - docker:dind

variables:
  IMAGE_URL: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"

before_script:
  - docker login -u gitlab-ci-token -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"

Build Images:
  stage: build
  script:
    - ./docker_build.sh
    - docker push "${IMAGE_URL}"

Publish to Docker Hub:
  stage: publish
  variables:
    HUB_IMAGE_URL: ${DOCKER_HUB_IMAGE}:latest
  script:
    - docker pull "${IMAGE_URL}"
    - >
      docker login
      -u "${DOCKER_HUB_USERNAME}"
      -p "${DOCKER_HUB_PASSWORD}"
      registry.hub.docker.com
    - docker tag "${IMAGE_URL}" "${HUB_IMAGE_URL}"
    - docker push "${HUB_IMAGE_URL}"
  only:
    - master

Publish to GitHub:
  image: alpine:3.7
  stage: publish
  before_script:
    - export SSH_DIR="${HOME}/.ssh"
    - apk add --update git openssh
  script:
    - '[ ! -d "${SSH_DIR}" ] && mkdir -p "${SSH_DIR}"'
    - >
      base64 -d <<< "${SSH_ZEROCUBE_DELIVERY_PRIVATE_KEY}"
      | dd of="${SSH_DIR}/.ssh"
    - git config user.name "${GITLAB_USER_NAME} (${GITLAB_USER_LOGIN})"
    - git config user.email "${GITLAB_USER_EMAIL}"
    - git remote set-url origin "${GITHUB_REPO}"
    - git push "${GITHUB_REPO}"
  only:
    - master